apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: prometheus-2
spec:
  forProvider:
    description: "Prometheus"
    securityGroup: "sks"
    type: "INGRESS"
    protocol: "TCP"
    startPort: 10251
    endPort: 10255
    userSecurityGroup: "sks"
  providerConfigRef:
    name: exoscale
