apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster
  labels:
    crossplane.io/xrd: xclusters.sks.exoscale.com
    provider: exoscale
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: sks.exoscale.com/v1alpha1
    kind: XCluster
  resources:
  - name: cluster
    base:
      apiVersion: sks.exoscale.jet.crossplane.io/v1alpha1
      kind: Cluster
      spec:
        forProvider:
          description: "Managed with Crossplane Exoscale Provider"
          zone: "de-fra-1"
          name: "CLUSTER_DISPLAY_NAME"
        providerConfigRef:
          name: "exoscale"
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.name
      toFieldPath: spec.forProvider.name
  - name: securitygroup
    base:
      apiVersion: securitygroup.exoscale.jet.crossplane.io/v1alpha1
      kind: SecurityGroup
      spec:
        forProvider:
          name: "SECURITYGROUP_DISPLAY_NAME"
          description: "this is a SG for SKS cluster"
        providerConfigRef:
          name: exoscale
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.name
      toFieldPath: spec.forProvider.name
  - name: sg_rule_calico
    base:
      apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Calico"
          securityGroupIdSelector:
            matchControllerRef: true
          type: "INGRESS"
          protocol: "UDP"
          startPort: 4789
          endPort: 4789
          userSecurityGroupIdSelector:
            matchControllerRef: true
        providerConfigRef:
          name: exoscale
  - name: sg_rule_kubelet
    base:
      apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Kubelet"
          securityGroupIdSelector:
            matchControllerRef: true
          type: "INGRESS"
          protocol: "TCP"
          startPort: 10250
          endPort: 10250
          userSecurityGroupIdSelector:
            matchControllerRef: true
        providerConfigRef:
          name: exoscale 
  - name: sg_rule_nodeport
    base:
      apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Node ports"
          securityGroupIdSelector:
            matchControllerRef: true
          type: "INGRESS"
          protocol: "TCP"
          startPort: 30000
          endPort: 32767
          cidr: "0.0.0.0/0"
        providerConfigRef:
          name: exoscale
  - name: sg_rule_prometheus_1
    base:
      apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Prometheus"
          securityGroupIdSelector:
            matchControllerRef: true
          type: "INGRESS"
          protocol: "TCP"
          startPort: 9100
          endPort: 9100
          userSecurityGroupIdSelector:
            matchControllerRef: true
        providerConfigRef:
          name: exoscale
  - name: sg_rule_prometheus_2
    base:
      apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
      kind: SecurityGroupRule
      spec:
        forProvider:
          description: "Prometheus"
          securityGroupIdSelector:
            matchControllerRef: true
          type: "INGRESS"
          protocol: "TCP"
          startPort: 10251
          endPort: 10251
          userSecurityGroupIdSelector:
            matchControllerRef: true
        providerConfigRef:
          name: exoscale
  - name: nodepool
    base:
      apiVersion: sks.exoscale.jet.crossplane.io/v1alpha1
      kind: Nodepool
      spec:
        forProvider:
          name: "NODEPOOL_DISPLAY_NAME"
          zone: "de-fra-1"
          instanceType: "standard.medium"
          size: 2
          clusterIdSelector:
            matchControllerRef: true
          securityGroupIdSelector:
            matchControllerRef: true
        providerConfigRef:
          name: "exoscale"
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.name
      toFieldPath: spec.forProvider.name
