apiVersion: exoscale.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: exoscale
spec:
  credentials:
    source: Secret
    secretRef:
      name: exoscale-creds
      namespace: crossplane-system
      key: credentials
