apiVersion: securitygroup.exoscale.jet.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  name: sks
spec:
  forProvider:
    name: "sks"
    description: "this is a SG for SKS cluster"
  providerConfigRef:
    name: exoscale
---
apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: calico
spec:
  forProvider:
    description: "Calico"
    securityGroupIdRef:
      name: sks
    type: "INGRESS"
    protocol: "UDP"
    startPort: 4789
    endPort: 4789
    userSecurityGroupIdRef:
      name: sks
  providerConfigRef:
    name: exoscale
---
apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: kubelet
spec:
  forProvider:
    description: "Kubelet"
    securityGroupIdRef:
      name: sks
    type: "INGRESS"
    protocol: "TCP"
    startPort: 10250
    endPort: 10250
    userSecurityGroupIdRef:
      name: sks
  providerConfigRef:
    name: exoscale
---
apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: nodeport
spec:
  forProvider:
    description: "Node ports"
    securityGroupIdRef:
      name: sks
    type: "INGRESS"
    protocol: "TCP"
    startPort: 30000
    endPort: 32767
    cidr: "0.0.0.0/0"
  providerConfigRef:
    name: exoscale
---
apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: prometheus-1
spec:
  forProvider:
    description: "Prometheus"
    securityGroupIdRef:
      name: sks
    type: "INGRESS"
    protocol: "TCP"
    startPort: 9100
    endPort: 9100
    userSecurityGroupIdRef:
      name: sks
  providerConfigRef:
    name: exoscale
---
apiVersion: securitygrouprule.exoscale.jet.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: prometheus-2
spec:
  forProvider:
    description: "Prometheus"
    securityGroupIdRef:
      name: sks
    type: "INGRESS"
    protocol: "TCP"
    startPort: 10251
    endPort: 10255
    userSecurityGroupIdRef:
      name: sks
  providerConfigRef:
    name: exoscale
---
apiVersion: sks.exoscale.jet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: demo
spec:
  forProvider:
    description: "Managed with Crossplane Exoscale Provider (generated with Terrajet)"
    zone: "de-fra-1"
    name: "demo"
  providerConfigRef:
    name: exoscale
---
apiVersion: sks.exoscale.jet.crossplane.io/v1alpha1
kind: Nodepool
metadata:
  name: demo
spec:
  forProvider:
    clusterIdRef:
      name: demo
    securityGroupIdRefs:
    - name: sks
    zone: "de-fra-1"
    name: "demo"
    instanceType: "standard.medium"
    size: 2
  providerConfigRef:
    name: exoscale
