apiVersion: compute.exoscale.jet.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: demo
spec:
  forProvider:
    displayName: "demo"
    zone: "de-fra-1"
    diskSize: 30
    template: "Linux Ubuntu 20.04 LTS 64-bit"
    securityGroups: ["default"]
  providerConfigRef:
    name: exoscale
