apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.sks.exoscale.com
spec:
  claimNames:
    kind: Cluster
    plural: clusters
  group: sks.exoscale.com
  names:
    kind: XCluster
    plural: xclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
            required:
            - parameters
